name: CMake on a single platform

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '432412eecac55981cf608cc12e5b4bd91768ec57'

    - name: Configure & Build with CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-release'
        buildPreset: 'ninja-release'