name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      VCPKG_BINARY_SOURCES: default,readwrite
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-bincache

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf-archive libltdl-dev libx11-dev libxft-dev libxext-dev \
          libxi-dev libxtst-dev libwayland-dev libxkbcommon-dev \
          libegl1-mesa-dev libibus-1.0-dev libgles2-mesa-dev libxrandr-dev

    - name: Remove MinGW compilers
      if: runner.os == 'Windows'
      shell: pwsh
      run: Rename-Item C:\mingw64 mingw64_

    - name: Remove MinGW compilers
      if: runner.os == 'Windows'
      shell: pwsh
      run: Rename-Item C:\Strawberry Strawberry_

    - name: Remove MinGW compilers
      if: runner.os == 'Windows'
      shell: pwsh
      run: Rename-Item "C:\Program Files\LLVM" LLVM_

    - name: Setup CMake
      uses: lukka/get-cmake@v4.3.3

    - name: Create binary cache directory
      shell: bash
      run: mkdir -p "${{ env.VCPKG_DEFAULT_BINARY_CACHE }}"

    - name: Set up vcpkg binary cache
      uses: actions/cache@v5
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg*.json') }}
        restore-keys: vcpkg-${{ matrix.os }}-

    - name: Configure CMake
      run: >
        cmake -B build -G "Ninja"
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/artifact
        -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: Output-${{ runner.os }}
        path: ${{ github.workspace }}/artifact
        if-no-files-found: error
